#!/usr/bin/env node
// Vendor the two web fonts into the repo.
//
// Hot-linking fonts.googleapis.com sends every visitor's IP to Google before
// the page has asked them anything, which is the one thing a German site
// really should not do. Self-hosting also removes two DNS lookups and a
// round trip from the critical path.
//
// Only the latin and latin-ext subsets are kept: the atlas is German place
// names and English or German prose, so Cyrillic, Greek and Vietnamese are
// weight for nobody. Google's own unicode-range lines are preserved, so a
// character outside the subset still falls back cleanly.
//
//   node scripts/vendor-fonts.mjs
//
// Both families are SIL Open Font License 1.1; OFL.txt sits beside them.

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'apps', 'web', 'public', 'fonts');
const CSS_OUT = join(ROOT, 'apps', 'web', 'src', 'design', 'fonts.css');

// Google serves a different CSS per user agent; this one gets woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  { name: 'Instrument Serif', query: 'Instrument+Serif:ital,wght@0,400;1,400' },
  { name: 'Inter', query: 'Inter:wght@400;500;600' },
];

const KEEP = new Set(['latin', 'latin-ext']);

/** Split Google's stylesheet into blocks, each tagged by its subset comment. */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let match;
  while ((match = re.exec(css))) {
    const [, subset, body] = match;
    const field = (name) => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1]?.trim();
    const url = body.match(/url\((https:[^)]+)\)/)?.[1];
    if (!url) continue;
    faces.push({
      subset,
      family: field('font-family')?.replace(/['"]/g, ''),
      style: field('font-style') ?? 'normal',
      weight: field('font-weight') ?? '400',
      range: field('unicode-range'),
      url,
    });
  }
  return faces;
}

const slug = (face) =>
  `${face.family.toLowerCase().replace(/\s+/g, '-')}-${face.weight}${
    face.style === 'italic' ? '-italic' : ''
  }-${face.subset}.woff2`;

async function main() {
  await mkdir(OUT, { recursive: true });
  const blocks = [];
  let bytes = 0;

  for (const family of FAMILIES) {
    const res = await fetch(
      `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`,
      { headers: { 'User-Agent': UA } },
    );
    if (!res.ok) throw new Error(`${family.name}: stylesheet ${res.status}`);
    const faces = parseFaces(await res.text()).filter((f) => KEEP.has(f.subset));
    if (!faces.length) throw new Error(`${family.name}: no latin faces found`);

    for (const face of faces) {
      const file = slug(face);
      const data = new Uint8Array(await (await fetch(face.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
      await writeFile(join(OUT, file), data);
      bytes += data.byteLength;
      blocks.push(
        `@font-face {\n` +
          `  font-family: '${face.family}';\n` +
          `  font-style: ${face.style};\n` +
          `  font-weight: ${face.weight};\n` +
          `  font-display: swap;\n` +
          `  src: url('/fonts/${file}') format('woff2');\n` +
          `  unicode-range: ${face.range};\n` +
          `}`,
      );
      console.log(`  ${file}  ${(data.byteLength / 1024).toFixed(1)} kB`);
    }
  }

  const header =
    `/* Generated by scripts/vendor-fonts.mjs — do not edit by hand.\n` +
    ` * Instrument Serif and Inter, latin and latin-ext only, served from\n` +
    ` * this origin so no visitor is announced to a font CDN.\n` +
    ` * Both families are SIL Open Font License 1.1 (public/fonts/OFL.txt). */\n\n`;
  await writeFile(CSS_OUT, header + blocks.join('\n\n') + '\n', 'utf8');
  console.log(`\n${blocks.length} faces, ${(bytes / 1024).toFixed(0)} kB total`);
  console.log(`wrote ${CSS_OUT}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
